packages:
  # all packages in subdirs of components/
  - 'firm/mmb/*'
  - 'element-plus-lib/**'
  - 'element-ui-lib/**'
  - 'rainbow-cli/**'
  - 'rainbow-css/**'
  - 'rainbow-js/**'
  - 'rainbow-ui/**'
  - 'rainbow-utils/**'
  - 'rainbow-view/**'
  
 


 